name: Package

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  release:
    types: [published]

jobs:
  package:
    runs-on: ${{ matrix.OS }}
    strategy:
      matrix:
        OS: ["ubuntu-latest", "windows-latest", "macos-latest"]
        include:
          # Replace "example" with the name your binary
          - os: macOS-latest
            uploaded_filename: tgtg-x86_64-apple-darwin
            local_path: artifacts
          - os: ubuntu-latest
            uploaded_filename: tgtg-x86_64-pc-linux
            local_path: artifacts
          - os: windows-latest
            uploaded_filename: tgtg-x86_64-pc-win32.exe
            local_path: artifacts
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: coursier/cache-action@v6
      - uses: VirtusLab/scala-cli-setup@v1
        with:
          power: true
          jvm: "temurin:17"
      - name: Package app
        run: scala-cli package . -o "${{ matrix.local_path }}/${{ matrix.uploaded_filename }}" --native-image
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.uploaded_filename }}
          path: ${{ matrix.local_path }}
          if-no-files-found: error
          retention-days: 2
      - name: Upload release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ matrix.local_path }}
          asset_name: ${{ matrix.uploaded_filename }}
          asset_content_type: application/zip
  package-docker:
    # if: github.event_name == 'release'
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - uses: coursier/cache-action@v6
      - uses: VirtusLab/scala-cli-setup@v1
        with:
          power: true
          jvm: "temurin:17"
      - name: Package app
        run: scala-cli package . -o artifacts/tgtg --docker --docker-image-repository ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Tag Docker image
        run: docker tag ${{ env.REGISTRY}}/${{ env.IMAGE_NAME}} ${{ steps.meta.outputs.tags }}
      - name: Push Docker image
        run: docker push ${{ steps.meta.outputs.tags }}
